version: "3"
services:
  kakuninsan_app:
    build: ./
    image: kakuninsan_app
    container_name: kakuninsan_app
    volumes:
      - type: bind
        source: "./kakuninsan"
        target: "/var/kakuninsan/kakuninsan"
      - type: volume
        source: src
        target: "/var/kakuninsan/web/src"
    restart: always
    tty: true
  kakuninsan_nginx:
    build: ./web
    image: kakuninsan_nginx
    container_name: kakuninsan_nginx
    ports:
      - "8002:80"
    volumes:
      - type: volume
        source: src
        target: "/var/kakuninsan/web/src"
    restart: always

volumes:
  src:
